terraform/groups/ch-account-ui/main.tf

Bucket names need to be unique so using the FQDN

chore: use fqdn for bucket name

---

terraform/groups/ch-account-ui/profiles/live-eu-west-2/live/vars

The live URL hasn't been decided yet so we are setting a temporary one.

chore: set live service_name to temp value

---

terraform/groups/ch-account-ui/lambda/auth/index.js

Lambda@edge runs in the nearest region to the user so we need to specify the region for SSM and account for the region in the function name.

fix: add region to auth function

---

components/general-ui/interaction/CookieBanners.js

Updating link in cookie banner as per [IDAM-1489](https://companieshouse.atlassian.net/browse/IDAM-1489)
Original link - https://find-and-update.company-information.service.gov.uk/help/cookies
Correct link - https://ewf.companieshouse.gov.uk/cookies

update cookie banners to correct cookie link

---

services/lang/content-tokens.json
services/stages/HOME_YOUR_COMPANIES.js

Changes made: 
- Added heading: ‘People digitally authorised…’ 
- Added hint text: ‘Anyone with access…’ 
- Changed label for first column: ‘Name’ 
- Removed line break <br> in ‘Authorisation status’ 
- Removed ‘view’ label in last column (though this will still need a visually hidden label- for screen readers) 
- Removed ‘company number’ info and put the company number directly underneath the company name in grey instead (known as a ‘heading with caption’) 
- Removed line break <br> in address 
Resolves: [IDAM-1496](https://companieshouse.atlassian.net/browse/IDAM-1496)

Layout changes

---

pages/account/manage.js

WHAT
remove company fetch from manage account page
WHY
We only want to call to get the data when we need it
HOW
update the config on the page

fix: remove company fetch from manage account page

---

components/application-specific/Loading.js
css/global.scss
pages/account/your-companies/index.js

WHAT
- Add a loading state for users while their list of associated companies is being retrieved
WHY
- Users with large amount of companies are being mis-informed when waiting for the companies to be retrieved 
HOW
- Add animation to loading component
- Add loading state to your companies page

feat: add loading state to your companies page

---

services/lang/content-tokens.json
services/stages/REQUEST_AUTH_CODE.js

PBI: https://companieshouse.atlassian.net/browse/IDAM-1594
WHAT
- We need to ensure we do not capture PII data in the service analytics
WHY
- So that we do not breach our corporate data privacy requirements
HOW
- pass the text without the company name into the analytics

fix: remove company name from matomo

---

components/general-ui/typeography/ErrorSummary.js
services/errors.js
services/forgerock.js
services/lang/tokens.json
tests/errors.test.js

WHAT  
At the moment Matomo logs reveal company names 
WHY  
This means security breaches.
HOW  
Separate the format of Matomo log from page displayed messages

Idam 1594/remove company name from log

---

pages/_document.js

WHAT
At the moment the application failed security scan. 
WHY
Failed because the application header does not include  'Content-Security-Policy'
HOW
Adds 'Content-Security-Policy'. to application, using combined minimum policies permissible by the application.

 add content security policy

---

pages/account/login.js
services/useFRAuth.js

WHAT
When a company is added and we get redirect to another site the company data is not refreshed.
WHY
We always want the customer data up to date
HOW
Add logic into the session storage allowing the company data to refresh

fix: add companies refresh logic to session

---

services/lang/content-tokens.json
services/stages/shared/emailOtp.js

PBI: https://companieshouse.atlassian.net/jira/software/c/projects/IDAM/boards/408?modal=detail&selectedIssue=IDAM-1582
WHAT
Add new hyperlink to send SMS to email OTP confirm if you have mobile number
WHY
Some customers may want to send an SMS if they have an issue with their email account
HOW
Update schema and add new text and component

feat: update sign in journey to make mobile otp optional for email

---

pages/account/your-companies/authorised-person.js
services/forgerock.js

WHAT: After the pagination change the page had no data being displayed
WHY: The page didn't have the context of what page it was on to get the right data to show
HOW: Update the link and pass the page number in where needed

fix: provide the right data for auth person companies page

---

terraform/groups/ch-account-ui/main.tf

IAM policies are malformed when IAM users' ARN are used in principals that don't exist.

Fixed S3 Bucket policy to reflect existing users in the principal

---

pages/account/your-companies/authorised-person.js
services/forgerock.js

Reverts companieshouse/ch-account-ui#588 as we need to put in a critical fix into production.

Revert "fix: provide the right data for auth person companies page"

---

pages/account/authorise/[pageStep].js
pages/account/your-companies/authorised-person.js

WHAT
Some links did not provided a page number causing some data not to be found
WHY
We always want to display the right information to the customer
HOW
Add the page number to the URL parameters

fix: update routing to include page number

---

services/forgerock.js

WHAT
Update more urls to include the correct url parameters
WHY
Without it the API cannot get the data
HOW
Add  params to URLs where needed

fix: update urls to include page number and search

---

pages/account/your-companies/index.js
services/pagination.js

WHAT  
Pagination displayed before page finished loading and last page not showing on some button clicks
WHY  
BUGS
HOW  
Pagination would only show when page has finished loading
Last page number would always show no matter pages selected

update to show pagination only when page loaded

---

services/stages/shared/emailOtp.js

WHAT
The analytics event was wrong for the OTP mobile link
WHY
We want to track all events properly
HOW
Update the text value

fix: change track event on mobile security code

---

services/stages/shared/emailOtp.js

WHAT
The analytics event was wrong for the OTP mobile link
WHY
We want to track all events properly
HOW
Update the text value

 add to fix show matomo mobile yp message

---

components/general-ui/interaction/CookieBanners.js

Added the govuk-body class to the required elements in the cookie-banner component in order for them to be displayed with the correct font.

added govuk-body class to cookie-banner p elements

---

services/lang/tokens.json

WHAT
Defined a new error token: INVITED_USER_GENERIC_ERROR.
WHY
Matomo was reporting instances of this error, yet the error was not defined in the tokens.json file.
HOW
Added an INVITED_USER_GENERIC_ERROR block in tokens.js that mirrors the content of INVITED_USER_ERROR (Unknown error occurred).

fix: CHAS-29 define missing error token

---

pages/account/manage.js
pages/account/manage/change-name/[pageStep].js
services/useFRAuth.js

This change is related to CHAS-24 which was raised to managed services. 
When a users changes their full name via the manage account page, the change is not reflected in the UI even though the name change was successful. 
We have resolved this in this PR.

fix change username not showing in UI

---

package-lock.json

WHAT 
12 critical security and 73 moderate vulnerabilities reported by Concourse pipeline deployment tests.
WHY 
Pipeline is blocked to other releases. Vulnerabilities need to be addressed.
HOW 
As advised on tests report, I run `npm audit fix` to mitigate vulnerabilities, while only issuing non-breaking changes. The ensuing report identifies 16 moderate and no critical vulnerabilities, which should allow the pipeline to run.

fix: security vulnerabilities CHAS-34

---

package-lock.json
services/lang/content-tokens.json
services/stages/shared/emailOtp.js

On the page where a user enters their OTP code there is a spelling mistake in the sentence: 
`"If you still have not recieved the email, we can "`
I have corrected the spelling of the word `received`
Bumped version from `4.2.1` to `4.2.2` to address the following high level vulnerability:
[browserify-sign upper bound check issue in `dsaVerify` leads to a signature forgery attack](https://github.com/advisories/GHSA-x9w5-v3q2-3rhw)

Chas43 fix spelling mistake

---

services/stages/REMOVE_USER_CONFIRM.js

We have discovered that this seems to be an issue with Matomo
I have removed the matomo track event from the cancel button on the remove user page to test if this works around the issue. 
Intention here is to test in dev to confirm workaround.

remove matomo track event from cancel button

---

services/lang/tokens.json

WHAT
Matomo is reporting missing error tokens in several user journeys.
WHY
This has an impact on analytics. Matomo is not able to retrieve accurate error data.
HOW
Three missing tokens added to `services/lang/tokens.json`
LOGIN_PASSWORD_CHECK_ERROR
RESET_PASSWORD_GENERIC_ERROR
REMOVE_USER_GENERIC_ERROR

fix: add more missing error tokens

---

services/lang/content-tokens.json

This change removes the company name for users on the "youNeedTheAuthenticationCode" page and associated analytics in Matamo

CHAS-27 remove company name

---

pages/account/manage/change-phone-number/[pageStep].js

When a user changes their phone number on the manage account page, the phone number is updated successfully, but the old phone number is still displayed to the user on the manage account page. 
This change implements the same fix we released for CHAS-24 in that we re-fetch the users profile information once the change has completed and update session storage to have the new phone number.

re-fetch profile on page load

---

services/lang/tokens.json

WHAT
Matomo analytics platform reports errors.
WHY
A few tokens, or snippets of text, that add Matomo content to each step in the user journey, were missing. So, the code was pointing to a token, but the token was missing. Companies House identified four specific tokens that needed to be addressed in ticket [CHAS-47](https://amidodevelopment.atlassian.net/browse/CHAS-47).
HOW
Added four new tokens to the services/lang/tokens.json file:
UNKNOWN_CREDENTIALS_MISSING_USERNAME
CREDENTIALS_MISSING_USERNAME
UNKNOWN_CREDENTIALS_MISSING_PASSWORD
CREDENTIALS_MISSING_PASSWORD

fix: missing matomo tokens

---

.husky/pre-commit
Makefile

Address vulnerabilities for ch-account-ui repo.
The pipeline is failing due to an error `npm ERR! audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable`.
Revert previous commit which did not fix the issue.

Revert previous change

---

services/stages/WEBFILING.js

###WHAT
Conditions added to parts of the message showing in auth code success page
###WHY
Error message that should be linked to failure is being shown when user has succeeded at requesting an auth code.
###HOW
Added the condition that a component is shown on error to each component shown on the page

fix: add conditions auth code error
