components/application-specific/BrowserTitle.js, components/forgerock-ui/ChoiceCallback.js, components/forgerock-ui/DisplayUiElements.js, components/forgerock-ui/NameCallback.js, components/forgerock-ui/PasswordCallback.js, components/forgerock-ui/StringAttributeInputCallback.js, components/forgerock-ui/ValidatedCreatePasswordCallback.js, components/general-ui/UiFeatures.js, pages/account/login.js, pages/account/register/[pageStep].js, pages/password-recovery/[pageStep].js, services/forgerock.js, services/lang/en.json
More updates based on the collaborative changes we've made this evening to the forgotten password flow. Also includes some fixes for UI E2E tests support requested by CH.
=> Idam 225 bug fixes

components/general-ui/typeography/ErrorSummary.js, components/views/FeatureDynamicView.js, pages/account/home.js, pages/account/login.js, pages/account/register/[pageStep].js, pages/am/XUI.js, pages/index.js, pages/password-recovery/[pageStep].js, services/forgerock.js, services/lang/cy/tokens.json, services/lang/en/tokens.json, services/translate.js
This PR includes:
- Switching off UI-based validation completely at the form level (novalidation on <form>)
- Better token handling so we can define error tokens for individual fields
- Updates to forgerock helper service to normalise errors coming in from failedPolicies array in callback data
=> Tweaks to the system

components/application-specific/InfoBlocks.js, components/general-ui/UiFeatures.js, components/general-ui/typeography/HeadingText.js, pages/_app.js, pages/account/associate/[pageStep].js, pages/account/home.js, pages/account/login.js, pages/account/logout.js, pages/account/register/[pageStep].js, pages/account/request-auth-code/[pageStep].js, pages/am/XUI.js, pages/password-recovery/[pageStep].js, services/forgerock.js, services/lang/en/features.json, services/lang/en/tokens.json, services/queryString.js, services/translate.js
Fixes and updates to the code to satisfy SonarQube scanner results
=> Sonar fixes

components/general-ui/UiFeatures.js, services/lang/en/features.json
Removed the counts from the "services" section of the home page as the new design doesn't have them
=> Homepage feature update

services/lang/en/features.json
Added the stage to support new error stage "LIMIT_EXCEEDED_ERROR"
=> Added a LIMIT_EXCEEDED_ERROR stage to features.json

components/general-ui/interaction/InputField.js
=> Remove aria when no related error for input

services/environment.js
To be merged once FR cert has been generated
=> Update FR config with custom domain

.husky/pre-commit, Makefile, package-lock.json, package.json
Will confirm that the --audit-level=high flag is acceptable but adding for now to get dev pipeline running again
=> Update vulnerable deps and add npm audit as pre-commit hook

components/general-ui/typeography/NotificationBanner.js, pages/account/authorise/[pageStep].js, services/forgerock.js, services/lang/en/features.json
Passing the notification id over to the your companies page in redirect after successfully adding a user
=> Add notification id to DOM after redirect

components/application-specific/InfoBlock.js, components/general-ui/typeography/HeadingText.js, components/views/FeatureDynamicView.js, pages/_app.js, pages/_document.js, pages/account/home.js, services/lang/en/homeStages.js
- Fix issue where footer did not fill to bottom of the page
- Remove incorrect warning from header component
=> Fix minor issue with footer spacing

components/Dynamic.js, components/forgerock-ui/DisplayUiElements.js, components/general-ui/UiFeatures.js, next.config.js, package-lock.json, package.json, pages/account/associate/[pageStep].js, pages/account/authorise/[pageStep].js, pages/account/home.js, pages/account/manage/change-password/[pageStep].js, pages/account/manage/change-phone-number/[pageStep].js, pages/account/notifications.js, pages/account/register/[pageStep].js, pages/account/request-auth-code/[pageStep].js, pages/account/your-companies/index.js, pages/password-recovery/[pageStep].js, services/forgerock.js, services/log.js, services/useFRAuth.js
Quick change to tidy up the client logging and disable outside of dev incase it's flagged as a PEN testing issue.
=> Standardise logging and disable outside of dev

package-lock.json, package.json, pages/account/associate/[pageStep].js, pages/account/login.js, services/mappings.js
=> Add display mappings for company data

components/application-specific/InfoBlock.js, components/application-specific/Loading.js, components/general-ui/interaction/Button.js, pages/account/login.js, pages/account/manage.js, pages/account/your-companies/index.js, services/forgerock.js, services/useFRAuth.js, services/useFRFlow.js
I've extracted the logic for navigating the FR flows and fetching company date here. This needed tidying up but also means we can handle the loading state in one place. I'll need to apply this extraction across all the pages but didn't want to make this PR too big.
=> Idam 741 loading state

pages/account/associate/[pageStep].js, pages/account/home.js, pages/account/login.js, pages/account/manage/change-email/[pageStep].js, pages/account/your-companies/index.js, pages/password-recovery/[pageStep].js, services/lang/content-tokens.json, services/stages/CH_LOGIN_1.js, services/stages/COMPANY_ASSOCIATION_3.js, services/stages/COMPANY_ASSOCIATION_4.js, services/stages/EWF_LOGIN_1.js, services/stages/HOME_YOUR_COMPANIES.js, services/stages/RESET_PASSWORD_5.js, services/stages/shared/emailOtp.js, services/useFRFlow.js, stories/pages/account/login.stories.js
- Update notifications to use new pattern and resolve & bug - IDAM-759
- Refactoring the affected journeys to use the shared FR flow hook
- Minor content updated IDAM-788 IDAM-783
=> Fix notifications and refactor affected journeys

components/general-ui/interaction/PhaseBanner.js, package-lock.json, services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Added a banner message to EWF landing and sign on pages in readiness for the power-down.
=> Created banner messages for EWF

components/general-ui/Footer.js, services/environment.js
Updating footer links as per [IDAM-1488](https://companieshouse.atlassian.net/browse/IDAM-1488)
Links for cookies and accessibility currently link to kermit, and should link to live.
=> updating footer links to live url

services/environment.js, services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/translate.js
Resolves: [IDAM-1492](https://companieshouse.atlassian.net/browse/IDAM-1492)
=> Add "Help with signing in" link (IDAM-1492)

services/environment.js
Changed the default CH_BASE_EWF_URL to the live version
=> Changed default CH_BASE_EWF_URL to live url

package-lock.json
Concourse build was failing due to vulnerabilities. Incude=ing the package-lockjson file should resolve this.
=> Inlcuded package-lock

package-lock.json, package.json, services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Added banner messages to web-filing screen 9 landing / sign-on)
=> add banner messages to web-filing screens

components/general-ui/typeography/SummaryList.js, package-lock.json
test of the build with new package-lock file
=> IDAM-1500: adding a comment

pages/account/your-companies/authorised-person.js, pages/account/your-companies/index.js
=> perf: search count logic was returning null

package-lock.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removal of banner messages on web-filing
=> remove banner messages to web-filing screens

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removal of essential maintenance banner message from WEB - Filing screens ( landing and sign-on )
=> remove banner messages from web-filing screens

services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
adding Essential Maintenance Banner message to Web-Filing landing / Sign-on screen
=> add banner messages to web-filing screens: 15/12/2022

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removal of the Essential Maintenance Banner from Web-Filing
=> Removal of Banner Messages from Web-Filing

services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Add banner messages to sign-on and landing page on web-filing.
=> update banner message for web-filing pages

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removing banner message from landing and sign-on pages ( Web Filing )
=> Remove banner message from landing and sign-on pages ( Web Filing )

services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Updated the landing and sign-on pages for EWF
=> Updating EWF Landing and sign-on pages

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
removal of banner messages from landing and sign-on page web-filing
=> removal of banner messages from landing and sign-on page web-filing

services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Updating Web-Filing landing and sign-in page
=> Updating Web-Filing landing and sign-in page

services/lang/content-tokens.json, services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
updating content-token.json and dependencies for new token
=> updating content-token.json and dependencies for new token

services/stages/EWF_LOGIN_1.js
Updating content-token.json and dependencies for new tokenFix
=> updating content-token.json and dependencies for new tokenFix

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Reverting the banner message from landing / sign-on page.  (Web-Filing)
=> Removal of banner messages from landing / sign-on pages

services/lang/content-tokens.json
Updating banner message for Web-Filing landing / sign-on page
=> updating banner message for Web-Filing landing and sign-on page

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removing of Banner Message from EWF landing / sign-on pages.
=> Removal of Banner Message from EWF landing / sign-on pages

.github/workflows/node.js.yaml
WHAT
Create a Github pipeline to test code before it is merged into master.
WHY
We need to ensure all code is tested before it is merged.
We need to ensure all environmental factors are ruled out when testing.
HOW
Create a Github workflow to build, lint and test the code before it can be merged in.
=> feat: create ci pipeline

README.md
=> trigger pipeline no changes

services/lang/content-tokens.json, services/stages/EWF_LOGIN_5.js, services/stages/REMOVE_USER_CONFIRM.js
WHAT
- fix current issues with our logging
WHY
- we want the logs to be clean and accurate
HOW
- update the references to the text outputted
BEFORE:
=> fix: update matamo logging

services/stages/EWF_LOGIN_1.js, services/stages/LOGIN.js
Removal of the current information message from sign-on and landing page. ( Web Filing ).
=> Removing the Information Banner Message from landing / sign-on page

components/general-ui/interaction/Pagination.js, components/general-ui/interaction/Pagination.stories.js, components/general-ui/interaction/Pagination.test.js, components/views/FeatureDynamicView.js, css/global.scss, pages/account/your-companies/index.js, services/forgerock.js, services/useFRAuth.js
WHAT
Use pagination component on Yourcompanies in readiness for ForgeRock API changes
WHY
To improve page loading performances when a user has multiple companies to display
HOW
Add Pagination included on the page passing essential props.
=> Idam 509/UI pagination

components/general-ui/interaction/Pagination.js, components/general-ui/interaction/Pagination.stories.js, components/general-ui/interaction/Pagination.test.js, components/views/FeatureDynamicView.js, css/global.scss, pages/account/your-companies/index.js, services/forgerock.js, services/useFRAuth.js
Reverts companieshouse/ch-account-ui#585 as we need to push a critical fix to production
=> Revert "Idam 509/UI pagination"

terraform/groups/ch-account-ui/locals.tf, terraform/groups/ch-account-ui/main.tf, terraform/groups/ch-account-ui/profiles/development-eu-west-2/development/vars, terraform/groups/ch-account-ui/profiles/live-eu-west-2/live/vars, terraform/groups/ch-account-ui/profiles/staging-eu-west-2/staging/vars, terraform/groups/ch-account-ui/variables.tf, terraform/groups/ch-account-ui/vault-providers/approle, terraform/groups/ch-account-ui/vault-providers/token, terraform/groups/ch-account-ui/vault-providers/userpass, terraform/groups/ch-account-ui/vault.tf
Added Vault config and data lookup for secrets
Added locals to extract role ARN list from Vault data
Appended ARN list to existing `identifiers` list - moved logic in to `locals.tf` to clean up resource code
Cleaned up profile vars to remove users that aren't required
Set default for `region` variable
=> Amend bucket policy

terraform/groups/ch-account-ui/main.tf
See: https://serverfault.com/a/815741
=> CHAS-10 Redirect 403 to index.html as website is SPA

terraform/groups/ch-account-ui/locals.tf
Updated `website_iam_policy_identifiers` local var to include additional ARNs sourced from Vault
=> Update IAM Policy

components/general-ui/interaction/Pagination.js, components/general-ui/interaction/Pagination.stories.js, components/general-ui/interaction/Pagination.test.js, components/views/FeatureDynamicView.js, css/global.scss, pages/account/your-companies/index.js, services/forgerock.js, services/useFRAuth.js
Reverts companieshouse/ch-account-ui#594
=> Add pagination logic back into codebase

pages/account/your-companies/authorised-person.js, services/forgerock.js
Reverts companieshouse/ch-account-ui#595
=> Revert: add pagination fix back into codebase

terraform/groups/ch-account-ui/main.tf
=> remove header

services/stages/LOGOUT_ERROR.js, services/stages/WEBFILING.js
WHAT  
"Contact Companies House" not display in welsh
WHY  
Configuration not applied
HOW  
"Contact Companies House"now in welsh with applied configuration
=> add to show contact company link in welsh

pages/account/authorise/[pageStep].js, pages/account/your-companies/authorised-person.js, pages/account/your-companies/index.js, services/forgerock.js
WHAT: Enable pagination search
WHY: Everything has to be paginated for the pagination data strategy to work
HOW: Change search to be provided from URL parameters and pass to appropriate links if exist
=> feat: add pagination search

pages/account/your-companies/index.js
WHAT
Ensure all pagination links work as expected
WHY
We need to have the correct url params on each page
HOW
Updated pagination urls and search count
=> fix: ensure all pagination urls are correct and update search count

pages/account/your-companies/authorised-person.js
WHAT
The URl parameter was wrong when generated
WHY
it should be search not companiesSearch so it is causing the data not to come back
HOW
change the key in the object
=> fix: change url param name

services/stages/shared/emailOtp.js
Reverts companieshouse/ch-account-ui#622
=> Revert "fix: change track event on mobile security code"

services/lang/content-tokens.json, services/stages/ONBOARDING_ERROR.js
WHAT
Error page reconfigured on branch CHAS-14 was missing a list number and a few improvements added to the text.
WHY
Correction was needed for the content to be complete.
HOW
Added a span text component, a text token and corrected a typo.
=> Chas 14 correct onboarding error message

terraform/groups/ch-account-ui/main.tf
Added comment to Cloudfront distribution
Minor alignment tweak
=> Add Cloudfront Distribution Comment

README.md
This is an empty commit, merging it will run the pipeline for ch-account-ui so I can see the results of NPM testing.
=> Empty commit to force pipeline to run

README.md, package-lock.json, package.json
Regenerate `package-lock.json`
Need to run the ch-account-ui pipeline again for node v18
Rerun `npm install` and `npm update` to generate the package lock file
=> Update package-lock file
